### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by lrojas94** [conradlo/react-pinch-and-zoom#5]
```
/home/luis/Work/waldo-web-next/node_modules/react-pinch-and-zoom/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as PropTypes from 'prop-types';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/home/luis/Work/waldo-web-next/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/home/luis/Work/waldo-web-next/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

```

I suppose this is happening because rather than transpiling the final result with Babel all you're doing is using TS to parse it.

I'll try making a PR later on, but as it is, this is sadly unusable to me :cry: 

Great project tho! Nice and simple integration you got there

**Comment by conradlo** [comment]
Hi, ts config was updated in latest patch, which will now target es5 and use commonjs module instead
